// ---------------------------------------------------------------------------
// Phase 0 prototype feed — 24 fictional examples.
//
// Everything here is FAKE and clearly presented as such in the UI. Stories are
// written to respect the platform's core safety rule:
//   "Tell your story. Never expose theirs."
// => no real names, no accusations of crimes, no identifying third-party data.
// ---------------------------------------------------------------------------

import type { FeedItem, ReactionKey } from "./types";

function r(partial: Partial<Record<ReactionKey, number>>): Record<ReactionKey, number> {
  return {
    dead: partial.dead ?? 0,
    red_flag: partial.red_flag ?? 0,
    tea: partial.tea ?? 0,
    good_for_you: partial.good_for_you ?? 0,
    sending_love: partial.sending_love ?? 0,
    savage: partial.savage ?? 0,
  };
}

export const FEED: FeedItem[] = [
  {
    id: "fy-001",
    slug: "macbook-pro-after-a-four-year-relationship",
    title: "MacBook Pro 14”",
    category: "electronics",
    condition: "like_new",
    price: { amountMinor: 69000, currency: "EUR" },
    photo: "💻",
    accent: "#7c5cff",
    seller: { name: "Léa", city: "Lyon", countryCode: "FR", verified: true, rating: 4.9, sold: 12 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "At least they had taste",
      body: "He finished his master's degree. Apparently he also finished us. Barely used, still logged out of everything — I promise.",
      contexts: ["at_least_they_had_taste", "moving_out"],
    },
    reactions: r({ dead: 18400, tea: 3200, red_flag: 1100, good_for_you: 900 }),
    comments: 214,
    nextChapter: {
      emoji: "🌴",
      title: "My first solo trip",
      raised: { amountMinor: 69000, currency: "EUR" },
      target: { amountMinor: 150000, currency: "EUR" },
    },
  },
  {
    id: "fy-002",
    slug: "engagement-ring-wedding-that-never-happened",
    title: "Engagement ring",
    category: "jewelry",
    condition: "new",
    price: { amountMinor: 120000, currency: "EUR" },
    photo: "💍",
    accent: "#e05a8a",
    seller: { name: "Anonymous", city: "Paris", countryCode: "FR", verified: true, rating: 5.0, sold: 3 },
    story: {
      mode: "clean_break",
      visibility: "anonymous",
      headline: "The wedding got cancelled. The ring is lovely.",
      body: "Beautiful, ethically sourced, never worn down the aisle. It deserves a happier story than mine.",
      contexts: ["wedding_cancelled"],
    },
    reactions: r({ sending_love: 9800, good_for_you: 4200, tea: 2100 }),
    comments: 486,
    nextChapter: {
      emoji: "🏡",
      title: "Deposit for my own place",
      raised: { amountMinor: 84000, currency: "EUR" },
      target: { amountMinor: 300000, currency: "EUR" },
    },
  },
  {
    id: "fy-003",
    slug: "ps5-he-ghosted-me",
    title: "PlayStation 5 + 3 games",
    category: "gaming",
    condition: "very_good",
    price: { amountMinor: 32000, currency: "EUR" },
    photo: "🎮",
    accent: "#3a86ff",
    seller: { name: "Marco", city: "Milan", countryCode: "IT", verified: false, rating: 4.7, sold: 8 },
    story: {
      mode: "full_story",
      visibility: "public",
      headline: "Ghosted mid-tournament",
      body: "We were supposed to co-op through the winter. Instead I got read receipts. The console never ghosted me though — flawless.",
      contexts: ["ghosted"],
    },
    reactions: r({ dead: 12200, savage: 3400, tea: 2600, red_flag: 1800 }),
    comments: 173,
  },
  {
    id: "fy-004",
    slug: "espresso-machine-terrible-anniversary-gift",
    title: "Espresso machine",
    category: "home",
    condition: "good",
    price: { amountMinor: 14000, currency: "EUR" },
    photo: "☕",
    accent: "#b5651d",
    seller: { name: "Sofia", city: "Madrid", countryCode: "ES", verified: true, rating: 4.8, sold: 21 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "A gift that said a lot",
      body: "I don't drink coffee. I've never drunk coffee. Three years together and this was the gift. It works perfectly, for someone.",
      contexts: ["terrible_gift", "what_was_i_thinking"],
    },
    reactions: r({ dead: 22100, savage: 5600, tea: 3300 }),
    comments: 402,
    nextChapter: {
      emoji: "📸",
      title: "A camera that's actually me",
      raised: { amountMinor: 14000, currency: "EUR" },
      target: { amountMinor: 90000, currency: "EUR" },
    },
  },
  {
    id: "fy-005",
    slug: "designer-bag-moving-somewhere-new",
    title: "Designer shoulder bag",
    category: "luxury",
    condition: "very_good",
    price: { amountMinor: 89000, currency: "EUR" },
    photo: "👜",
    accent: "#c9a227",
    seller: { name: "Marie", city: "Paris", countryCode: "FR", verified: true, rating: 4.9, sold: 12 },
    story: {
      mode: "clean_break",
      visibility: "limited",
      headline: "Moving somewhere new",
      body: "Downsizing my life into two suitcases. This one has been to more cities than most people — time to let it explore without me.",
      contexts: ["moving_out", "peaceful_goodbye"],
    },
    reactions: r({ good_for_you: 15200, sending_love: 6100, tea: 900 }),
    comments: 258,
    nextChapter: {
      emoji: "🌍",
      title: "One-way ticket, new start",
      raised: { amountMinor: 124000, currency: "EUR" },
      target: { amountMinor: 200000, currency: "EUR" },
    },
    pastSold: true,
  },
  {
    id: "fy-006",
    slug: "road-bike-what-was-i-thinking",
    title: "Carbon road bike",
    category: "other",
    condition: "good",
    price: { amountMinor: 55000, currency: "EUR" },
    photo: "🚲",
    accent: "#2a9d8f",
    seller: { name: "Tom", city: "Amsterdam", countryCode: "NL", verified: false, rating: 4.6, sold: 5 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "Bought to impress someone who cycles",
      body: "I do not cycle. I have never cycled. I own exactly one story about this bike and it involves a very long, very silent Sunday.",
      contexts: ["what_was_i_thinking"],
    },
    reactions: r({ dead: 9900, tea: 2200, good_for_you: 1400 }),
    comments: 121,
  },
  {
    id: "fy-007",
    slug: "wedding-dress-never-worn",
    title: "Wedding dress (never worn)",
    category: "wedding",
    condition: "new",
    price: { amountMinor: 60000, currency: "EUR" },
    photo: "👗",
    accent: "#e8b4bc",
    seller: { name: "Anonymous", city: "Berlin", countryCode: "DE", verified: true, rating: 5.0, sold: 1 },
    story: {
      mode: "clean_break",
      visibility: "anonymous",
      headline: "It never made it down the aisle",
      body: "Tags still on. I hope it becomes the happiest day of someone else's life instead of the saddest of mine.",
      contexts: ["wedding_cancelled"],
    },
    reactions: r({ sending_love: 18700, good_for_you: 3900, tea: 700 }),
    comments: 631,
    nextChapter: {
      emoji: "🎓",
      title: "Back to university",
      raised: { amountMinor: 60000, currency: "EUR" },
      target: { amountMinor: 250000, currency: "EUR" },
    },
  },
  {
    id: "fy-008",
    slug: "watch-red-flags-i-ignored",
    title: "Automatic watch",
    category: "luxury",
    condition: "like_new",
    price: { amountMinor: 42000, currency: "EUR" },
    photo: "⌚",
    accent: "#264653",
    seller: { name: "Kevin", city: "Brussels", countryCode: "BE", verified: true, rating: 4.8, sold: 15 },
    story: {
      mode: "full_story",
      visibility: "public",
      headline: "Red flags I chose not to see",
      body: "Kept perfect time. Which is ironic, because I ignored every single warning sign right on schedule. Serviced, boxed, ready.",
      contexts: ["red_flags", "what_was_i_thinking"],
    },
    reactions: r({ red_flag: 14300, dead: 5200, savage: 2100 }),
    comments: 198,
  },
  {
    id: "fy-009",
    slug: "sofa-divorce-downsizing",
    title: "Two-seater sofa",
    category: "home",
    condition: "good",
    price: { amountMinor: 25000, currency: "EUR" },
    photo: "🛋️",
    accent: "#8d99ae",
    seller: { name: "Isabelle", city: "Toulouse", countryCode: "FR", verified: true, rating: 4.9, sold: 30 },
    story: {
      mode: "clean_break",
      visibility: "public",
      headline: "One life, now half the furniture",
      body: "The divorce was calm, the sofa is comfortable, and honestly I never liked the colour. New chapter, new couch.",
      contexts: ["divorce", "peaceful_goodbye"],
    },
    reactions: r({ good_for_you: 8300, sending_love: 2100, tea: 400 }),
    comments: 87,
    nextChapter: {
      emoji: "🎨",
      title: "Turning the spare room into a studio",
      raised: { amountMinor: 41000, currency: "EUR" },
      target: { amountMinor: 120000, currency: "EUR" },
    },
    pastSold: true,
  },
  {
    id: "fy-010",
    slug: "camera-solo-trip-fund",
    title: "Mirrorless camera",
    category: "electronics",
    condition: "very_good",
    price: { amountMinor: 47000, currency: "EUR" },
    photo: "📷",
    accent: "#457b9d",
    seller: { name: "Nadia", city: "Lisbon", countryCode: "PT", verified: false, rating: 4.7, sold: 6 },
    story: {
      mode: "clean_break",
      visibility: "public",
      headline: "It photographed a life I've outgrown",
      body: "Every photo on the card was of a version of me I'm done being. Wiped clean, working beautifully, ready for your version.",
      contexts: ["peaceful_goodbye", "moving_out"],
    },
    reactions: r({ good_for_you: 6600, sending_love: 3100, tea: 500 }),
    comments: 143,
    nextChapter: {
      emoji: "✈️",
      title: "Three months, one backpack",
      raised: { amountMinor: 47000, currency: "EUR" },
      target: { amountMinor: 180000, currency: "EUR" },
    },
  },
  {
    id: "fy-011",
    slug: "guitar-band-that-broke-up",
    title: "Electric guitar",
    category: "other",
    condition: "good",
    price: { amountMinor: 38000, currency: "EUR" },
    photo: "🎸",
    accent: "#e76f51",
    seller: { name: "Diego", city: "Barcelona", countryCode: "ES", verified: false, rating: 4.5, sold: 4 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "The band lasted one summer",
      body: "Two rehearsals, one argument about the setlist, zero gigs. Sounds incredible though. Someone please give it a real audience.",
      contexts: ["what_was_i_thinking"],
    },
    reactions: r({ dead: 7700, tea: 1900, good_for_you: 1200 }),
    comments: 96,
  },
  {
    id: "fy-012",
    slug: "sneakers-he-cheated",
    title: "Limited sneakers",
    category: "fashion",
    condition: "like_new",
    price: { amountMinor: 28000, currency: "EUR" },
    photo: "👟",
    accent: "#ef476f",
    seller: { name: "Anonymous", city: "Rome", countryCode: "IT", verified: true, rating: 4.9, sold: 9 },
    story: {
      mode: "clean_break",
      visibility: "anonymous",
      headline: "A clean break, in a size 43",
      body: "I'd rather not tell the whole story. Let's just say these barely touched the ground and neither did the relationship.",
      contexts: ["cheated_on"],
    },
    reactions: r({ sending_love: 5400, red_flag: 3300, savage: 1600, tea: 1200 }),
    comments: 175,
    nextChapter: {
      emoji: "💪",
      title: "A year of therapy and gym",
      raised: { amountMinor: 28000, currency: "EUR" },
      target: { amountMinor: 100000, currency: "EUR" },
    },
  },
  {
    id: "fy-013",
    slug: "kitchen-mixer-terrible-gift",
    title: "Stand mixer",
    category: "home",
    condition: "new",
    price: { amountMinor: 21000, currency: "EUR" },
    photo: "🧁",
    accent: "#ffb703",
    seller: { name: "Emma", city: "Vienna", countryCode: "AT", verified: true, rating: 4.8, sold: 18 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "\"You'll grow into baking\"",
      body: "Reader: I did not grow into baking. Still in the box. Comes with the recipe book I also never opened.",
      contexts: ["terrible_gift"],
    },
    reactions: r({ dead: 10200, tea: 2400, good_for_you: 800 }),
    comments: 134,
  },
  {
    id: "fy-014",
    slug: "vinyl-collection-moving-abroad",
    title: "Vinyl collection (80 records)",
    category: "collectibles",
    condition: "very_good",
    price: { amountMinor: 45000, currency: "EUR" },
    photo: "🎶",
    accent: "#6a4c93",
    seller: { name: "Hugo", city: "Bordeaux", countryCode: "FR", verified: true, rating: 5.0, sold: 25 },
    story: {
      mode: "clean_break",
      visibility: "public",
      headline: "Ten years of Sundays",
      body: "Every record is a memory and I'm out of shelf space and out of the country next month. Take good care of them.",
      contexts: ["moving_out", "peaceful_goodbye"],
    },
    reactions: r({ sending_love: 4800, good_for_you: 2600, tea: 300 }),
    comments: 72,
    nextChapter: {
      emoji: "🗽",
      title: "Starting over in a new country",
      raised: { amountMinor: 45000, currency: "EUR" },
      target: { amountMinor: 220000, currency: "EUR" },
    },
  },
  {
    id: "fy-015",
    slug: "gaming-pc-relationship-upgrade",
    title: "Gaming PC (RTX build)",
    category: "gaming",
    condition: "like_new",
    price: { amountMinor: 98000, currency: "EUR" },
    photo: "🖥️",
    accent: "#00b4d8",
    seller: { name: "Jonas", city: "Hamburg", countryCode: "DE", verified: true, rating: 4.9, sold: 11 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "\"It's me or the PC\"",
      body: "Bold ultimatum. I chose peace, then quietly kept losing sleep anyway. Water-cooled, dust-free, undefeated.",
      contexts: ["red_flags"],
    },
    reactions: r({ dead: 16800, savage: 4100, tea: 2200 }),
    comments: 289,
  },
  {
    id: "fy-016",
    slug: "handbag-at-least-good-taste",
    title: "Quilted handbag",
    category: "luxury",
    condition: "very_good",
    price: { amountMinor: 135000, currency: "EUR" },
    photo: "👛",
    accent: "#d4a373",
    seller: { name: "Anonymous", city: "Geneva", countryCode: "CH", verified: true, rating: 5.0, sold: 7 },
    story: {
      mode: "clean_break",
      visibility: "anonymous",
      headline: "At least they had taste",
      body: "The relationship was a mistake. The gift was not. Authenticated, pristine, and ready to be someone's treat to themselves.",
      contexts: ["at_least_they_had_taste"],
    },
    reactions: r({ good_for_you: 7200, tea: 3900, sending_love: 1500 }),
    comments: 210,
  },
  {
    id: "fy-017",
    slug: "ski-gear-couple-hobby",
    title: "Full ski set",
    category: "other",
    condition: "good",
    price: { amountMinor: 34000, currency: "EUR" },
    photo: "🎿",
    accent: "#48cae4",
    seller: { name: "Clara", city: "Grenoble", countryCode: "FR", verified: false, rating: 4.6, sold: 3 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "Our couple's hobby (I hated it)",
      body: "Turns out I don't like being cold, going fast, or the person who suggested both. Great gear though, genuinely.",
      contexts: ["peaceful_goodbye", "what_was_i_thinking"],
    },
    reactions: r({ dead: 6300, tea: 1600, good_for_you: 900 }),
    comments: 64,
  },
  {
    id: "fy-018",
    slug: "record-player-clean-break",
    title: "Turntable + speakers",
    category: "electronics",
    condition: "very_good",
    price: { amountMinor: 30000, currency: "EUR" },
    photo: "🔊",
    accent: "#f4a261",
    seller: { name: "Amina", city: "Marseille", countryCode: "FR", verified: true, rating: 4.9, sold: 14 },
    story: {
      mode: "clean_break",
      visibility: "public",
      headline: "Some soundtracks you retire",
      body: "It played every 'our song' we ever had. I'd like it to make brand-new memories for someone with better taste in exes.",
      contexts: ["peaceful_goodbye"],
    },
    reactions: r({ sending_love: 3900, good_for_you: 2200, tea: 700 }),
    comments: 58,
    nextChapter: {
      emoji: "🎧",
      title: "Learning to DJ",
      raised: { amountMinor: 30000, currency: "EUR" },
      target: { amountMinor: 80000, currency: "EUR" },
    },
  },
  {
    id: "fy-019",
    slug: "coat-winter-that-ended-things",
    title: "Wool overcoat",
    category: "fashion",
    condition: "like_new",
    price: { amountMinor: 24000, currency: "EUR" },
    photo: "🧥",
    accent: "#606c38",
    seller: { name: "Paul", city: "Nantes", countryCode: "FR", verified: false, rating: 4.7, sold: 6 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "Bought for a winter that ended early",
      body: "Warm, timeless, and worn exactly twice before things cooled down in every possible sense. Your winter, your rules.",
      contexts: ["ghosted"],
    },
    reactions: r({ dead: 4700, tea: 1300, good_for_you: 800 }),
    comments: 49,
  },
  {
    id: "fy-020",
    slug: "board-games-game-night-over",
    title: "Board game bundle (12)",
    category: "collectibles",
    condition: "good",
    price: { amountMinor: 12000, currency: "EUR" },
    photo: "🎲",
    accent: "#bc6c25",
    seller: { name: "Rita", city: "Porto", countryCode: "PT", verified: true, rating: 4.8, sold: 19 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "Game night doesn't survive a break-up",
      body: "Turns out you can't split custody of a co-op deck-builder. All complete, all pieces counted, all yours.",
      contexts: ["peaceful_goodbye"],
    },
    reactions: r({ dead: 5100, tea: 1700, good_for_you: 1000 }),
    comments: 71,
  },
  {
    id: "fy-021",
    slug: "perfume-set-terrible-taste",
    title: "Unopened perfume set",
    category: "fashion",
    condition: "new",
    price: { amountMinor: 9000, currency: "EUR" },
    photo: "🧴",
    accent: "#cdb4db",
    seller: { name: "Yasmin", city: "Antwerp", countryCode: "BE", verified: false, rating: 4.5, sold: 2 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "Not my scent, not my person",
      body: "A fragrance that smelled like someone else's idea of me. Sealed, boxed — go be a better match for it than I was.",
      contexts: ["terrible_gift", "what_was_i_thinking"],
    },
    reactions: r({ dead: 3800, tea: 1100, good_for_you: 600 }),
    comments: 33,
  },
  {
    id: "fy-022",
    slug: "drone-grand-plans",
    title: "Camera drone",
    category: "electronics",
    condition: "very_good",
    price: { amountMinor: 52000, currency: "EUR" },
    photo: "🚁",
    accent: "#219ebc",
    seller: { name: "Felix", city: "Munich", countryCode: "DE", verified: true, rating: 4.9, sold: 13 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "Bought for the trips we planned",
      body: "We were going to film the whole coast. We filmed the living room, twice. It flies perfectly and never planned a single thing.",
      contexts: ["peaceful_goodbye"],
    },
    reactions: r({ dead: 6800, tea: 2000, good_for_you: 1300 }),
    comments: 88,
    nextChapter: {
      emoji: "🎬",
      title: "Funding my first short film",
      raised: { amountMinor: 52000, currency: "EUR" },
      target: { amountMinor: 160000, currency: "EUR" },
    },
  },
  {
    id: "fy-023",
    slug: "necklace-peaceful-goodbye",
    title: "Gold necklace",
    category: "jewelry",
    condition: "like_new",
    price: { amountMinor: 41000, currency: "EUR" },
    photo: "📿",
    accent: "#ffd166",
    seller: { name: "Chloé", city: "Strasbourg", countryCode: "FR", verified: true, rating: 5.0, sold: 22 },
    story: {
      mode: "clean_break",
      visibility: "public",
      headline: "A kind goodbye",
      body: "We ended things gently and I kept this too long out of habit. No drama here — just a lovely piece looking for a fresh neck.",
      contexts: ["peaceful_goodbye"],
    },
    reactions: r({ sending_love: 5600, good_for_you: 2400, tea: 200 }),
    comments: 61,
  },
  {
    id: "fy-024",
    slug: "tent-outdoor-couple",
    title: "2-person tent + gear",
    category: "other",
    condition: "good",
    price: { amountMinor: 16000, currency: "EUR" },
    photo: "⛺",
    accent: "#3a5a40",
    seller: { name: "Ben", city: "Ghent", countryCode: "BE", verified: false, rating: 4.6, sold: 5 },
    story: {
      mode: "little_tea",
      visibility: "public",
      headline: "It fit two people. Then one.",
      body: "Bought for the great outdoors and the great 'us'. Only the outdoors delivered. Waterproof, tested, one small emotional dent.",
      contexts: ["moving_out"],
    },
    reactions: r({ dead: 5900, tea: 1500, good_for_you: 700 }),
    comments: 54,
  },
];

export function getFeedItem(slug: string): FeedItem | undefined {
  return FEED.find((f) => f.slug === slug);
}
